### ISSUE TITLE
decoding a jwt produces "invalid signature" error 

### ISSUE THREAD

**Issue by alaz-aura** [jwt-rs/jwt-ui#33]
**Describe the bug**
Decoding a jwt using jwt-ui produces an error yet the same jwt decoded in jwt.io does not show this error (message is "signature verified"

**To Reproduce**
Steps to reproduce the behavior or a screencast
1. Run jwt-ui
2. Copy+ paste an encoded jwt 
3. View results

**Expected behavior**
<img width="736" alt="Screenshot 2024-05-01 at 10 58 49 am" src="https://github.com/jwt-rs/jwt-ui/assets/144073715/a2b3d6e6-0d03-4afe-a73e-538c1cbbf7f3">

**Screenshots**

**Desktop (please complete the following information):**
 - OS and OS version: Mac 13.5.2
 - Terminal name and version: iTerm2 build 3.4.20
 - Shell name and version: zsh
 - jwt-ui version: jwt-ui 1.1.0

**Additional context**

**Comment by tolik518** [comment]
Same happens to me using the main branch of jwt-ui with the key provided in the unit tests `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.XbPfbIHMI6arZ3Y922BhjWgQzWXcXNrz0ogtVhfEd2o` will get me a `The JWT provided has an invalid signature: InvalidSignature`.

I'm using Ubuntu 20.04. The tests for me are passing though.

**Comment by tolik518** [comment]
hey @alaz-aura,

I don't know whats the intended workflow is, but the workflow I found would be the following:

```bash
# Get token data
jwtui -sn "eyJ0...."
```

Then you'd need to get the url form the `iss` from the output.
For example https://login.microsoftonline.com/8bc55320-052b-4b5f-a553-79c567cfafcd/v2.0/    
Now append `.well-known/openid-configuration` to it (this is standardized).  
Now you get JSON containing the `jwks_uri`, in this case its https://login.microsoftonline.com/8bc55320-052b-4b5f-a553-79c567cfafcd/discovery/v2.0/keys. 

This keys ur you can use now like this:
```bash
# Start UI with prefilled token to decode and JWKS secret from URL
jwtui -S $(curl https://login.microsoftonline.com/8bc55320-052b-4b5f-a553-79c567cfafcd/discovery/v2.0/keys) "eyJ0...."
```

So yeah, I'm all for automating that process by adding a `--online` keyword since signature verifying only works if you have gotten the keys from the issuer

**Comment by deepu105** [comment]
I need to look into this. It does decode the jwt even if signature is not verified right?

**Comment by tolik518** [comment]
Yeah, it still decides the JWT just fine

**Comment by deepu105** [comment]
Ok I took a look and IMO this is working as expected and the error is intentional. You need to pass a supported secret format or a JWKS for signature validation to work. This tool is meant to be fully offline so it wont automatically fetch JWKS. AFAIK jwt.io does not verify signature automatically for non JWKS secrets. For the samples loaded by default the secret is hardcoded on the UI so the signature will be verified. Try pasting a JWT from outside jwt.io and it will show signature validation. It only looks up JWKS when the token is using JWKS

**Comment by deepu105** [comment]
@tolik518 for valid json pass the `-j`

**Comment by deepu105** [comment]
@alaz-aura as @tolik518 suggested the workflow in this case would be to pass the JWKS using curl or download it once and pass the file so that JWT UI remains fully offline. The JWKS will remain the same for all tokens from the same tenant.
